In [7]:
import numpy


In [6]:
inputs_list = [1,2,3]
targets_list = [5,5,5]

In [12]:
inputs = numpy.array(inputs_list, ndmin=2).T
targets = numpy.array(targets_list, ndmin=2).T

In [13]:
inputs

array([[1],
       [2],
       [3]])

In [15]:
wih = numpy.zeros([3,3])

In [39]:
wih = numpy.random.normal(0.0, pow(3, -0.5), (3, 3))

In [49]:
who = numpy.random.normal(0.0, pow(3, -0.5), (3, 3))
who

array([[ 0.51771456,  0.1930628 , -0.09438124],
       [ 0.64838142, -0.70872041, -0.53059963],
       [-0.77339891,  0.08266008,  0.08499081]])

In [40]:
wih

array([[-0.3552989 ,  0.42279678, -0.01449485],
       [ 0.13459197, -1.55088288, -0.11870999],
       [-0.0786683 , -0.39298027, -0.09739265]])

In [41]:
numpy.dot(wih,inputs)

array([[ 0.44681011],
       [-3.32330377],
       [-1.15680681]])

In [25]:
import scipy.special

In [26]:
activation_function = lambda x: scipy.special.expit(x)

In [44]:
hidden_inputs = numpy.dot(wih, inputs)

In [45]:
hidden_inputs

array([[ 0.44681011],
       [-3.32330377],
       [-1.15680681]])

In [47]:
hidden_outputs = activation_function(hidden_inputs)

In [48]:
hidden_outputs

array([[ 0.60988054],
       [ 0.03478033],
       [ 0.23924799]])

In [50]:
final_inputs = numpy.dot(who, hidden_outputs)
final_inputs 

array([[ 0.2998783 ],
       [ 0.24384079],
       [-0.44847212]])

In [52]:
final_outputs = activation_function(final_inputs)
final_outputs

array([[ 0.57441277],
       [ 0.56065993],
       [ 0.38972409]])

In [53]:
output_errors = targets - final_outputs
output_errors

array([[ 4.42558723],
       [ 4.43934007],
       [ 4.61027591]])

In [54]:
who

array([[ 0.51771456,  0.1930628 , -0.09438124],
       [ 0.64838142, -0.70872041, -0.53059963],
       [-0.77339891,  0.08266008,  0.08499081]])

In [55]:
who.T

array([[ 0.51771456,  0.64838142, -0.77339891],
       [ 0.1930628 , -0.70872041,  0.08266008],
       [-0.09438124, -0.53059963,  0.08499081]])

In [56]:
hidden_errors = numpy.dot(who.T, output_errors) 
hidden_errors


array([[ 1.60399423],
       [-1.91074888],
       [-2.38137354]])

In [79]:
gradient = 0.3 * output_errors * final_outputs * (1-final_outputs)
gradient

array([[ 0.32456735],
       [ 0.32804997],
       [ 0.32895133]])

In [80]:
hidden_outputs_T = numpy.transpose(hidden_outputs)
hidden_outputs_T

array([[ 0.60988054,  0.03478033,  0.23924799]])

In [81]:
numpy.dot(gradient,hidden_outputs_T)

array([[ 0.19794731,  0.01128856,  0.07765209],
       [ 0.20007129,  0.01140969,  0.0784853 ],
       [ 0.20062102,  0.01144104,  0.07870095]])

In [78]:
0.3 * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))

array([[ 0.19794731,  0.01128856,  0.07765209],
       [ 0.20007129,  0.01140969,  0.0784853 ],
       [ 0.20062102,  0.01144104,  0.07870095]])

In [82]:
0.3 * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))

array([[ 0.11448971,  0.22897941,  0.34346912],
       [-0.01924353, -0.03848706, -0.05773059],
       [-0.13002899, -0.26005798, -0.39008696]])

In [83]:
who +=  0.3 * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))

In [84]:
who

array([[ 0.71566187,  0.20435136, -0.01672915],
       [ 0.84845271, -0.69731072, -0.45211433],
       [-0.57277789,  0.09410111,  0.16369175]])

In [85]:
wih += 0.3 * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))

In [86]:
wih

array([[-0.24080919,  0.65177619,  0.32897428],
       [ 0.11534844, -1.58936994, -0.17644058],
       [-0.20869729, -0.65303825, -0.48747962]])